# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-07 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ct_name', models.CharField(default=b'DEFAULT VALUE', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(default=b'DEFAULT VALUE', max_length=128)),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(default=b'DEFAULT VALUE', max_length=30)),
                ('c_url_photo', models.URLField(default=b'DEFAULT VALUE')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(default=b'DEFAULT VALUE', max_length=30)),
                ('g_member', models.CharField(default=b'DEFAULT VALUE', max_length=100)),
                ('g_content', models.TextField(blank=True, max_length=100, null=True)),
                ('g_state', models.CharField(default=b'DEFAULT VALUE', max_length=1)),
                ('g_createdtime', models.DateTimeField(auto_now_add=True)),
                ('g_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_city', to='books.City')),
                ('g_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_country', to='books.Country')),
            ],
            options={
                'ordering': ['-g_createdtime'],
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gm_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_group', to='books.Group')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default=b'DEFAULT VALUE', max_length=30)),
                ('username', models.CharField(default=b'DEFAULT VALUE', max_length=30)),
                ('password', models.CharField(default=b'DEFAULT VALUE', max_length=128)),
                ('firstname', models.CharField(default=b'DEFAULT VALUE', max_length=30)),
                ('lastname', models.CharField(default=b'DEFAULT VALUE', max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='groupmember',
            name='gm_member',
            field=models.ManyToManyField(related_name='member_group', to='books.User'),
        ),
        migrations.AddField(
            model_name='group',
            name='g_organiser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_organiser', to='books.User'),
        ),
        migrations.AddField(
            model_name='group',
            name='g_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_gatherplace', to='books.City'),
        ),
        migrations.AddField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_comment', to='books.Group'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to='books.User'),
        ),
        migrations.AddField(
            model_name='city',
            name='ct_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='City_Country', to='books.Country'),
        ),
    ]
